### ISSUE TITLE
GetGoogleImageSearchURLs outdated

### ISSUE THREAD

**Issue by tillnagel** [jeffThompson/ProcessingTeachingSketches#1]
Your GetGoogleImageSearchURLs example is outdated. The resulting HTML doesn't match your regexp, anymore. Find a working replacement for line 66 below.

https://github.com/jeffThompson/ProcessingTeachingSketches/blob/master/AdvancedTopics/GetGoogleImageSearchURLs/GetGoogleImageSearchURLs.pde#L66

`String[][] m = matchAll(source, "img height=\"\\d+\" src=\"([^\"]+)\"");`

**Comment by jeffThompson** [comment]
Updated, thanks for the fix!
