### ISSUE TITLE
RunUnixCommands.pde requires import

### ISSUE THREAD

**Issue by JKFennis** [jeffThompson/ProcessingTeachingSketches#2]
thanks for this collection for utilities!

just wanted to let you know that RunUnixCommands.pde needs the following import line to run: ```import java.io.*;```
It's so nice when 8yr old processing code still compiles and runs :)

**Comment by jeffThompson** [comment]
Cool, thanks! And glad these help! I'm not really maintaining this repo any more, since I've mostly moved my teaching stuff to class repos. A lot of the sketches here break because they use variables in `setup()`, a change that bums me out!

But thanks for sending the update!
